name: Run Tests

on:
  push:

  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  telescope-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Deps
        run: yarn && yarn bootstrap
      - name: test ast
        run: cd ./packages/ast && yarn test
      - name: test parser
        run: cd ./packages/parser && yarn test
      - name: test telescope
        run: cd ./packages/telescope && yarn test