name: Run Tests

on:
  push:

  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  telescope-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: install Deps
        run: yarn
      - name: bootstrap
        run: yarn bootstrap
      - name: build
        run: yarn build
      # - name: build parser
      #   run: cd ./packages/parser && yarn && yarn build
      # - name: build types
      #   run: cd ./packages/types && yarn && yarn build
      - name: test ast
        run: cd ./packages/ast && yarn test